EXECUTABLES=Lab1

SRC=Lab1.c

OBJ=Lab1.o

CC=gcc

CFLAGS=-g

all: $(EXECUTABLES)

$(EXECUTABLES): $(SRC)
	
	$(CC) $(CFLAGS) -c $(SRC)

	$(CC) $(CFLAGS) -o $@ $(OBJ)

clean:
	rm -f $(EXECUTABLES) $(OBJ) *~